dist: trusty
sudo: required
language: generic
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
script:
- sudo apt-get install zlib1g-dev
- wget https://curl.haxx.se/download/curl-7.54.0.tar.gz
- tar xvzf curl-7.54.0.tar.gz
- rm curl-7.54.0.tar.gz
- ls

- wget https://www.openssl.org/source/openssl-1.0.2l.tar.gz
- tar xvzf openssl-1.0.2l.tar.gz
- rm openssl-1.0.2l.tar.gz
- ls

- cd openssl-1.0.2l
- ./config --openssldir=/usr/local/ssl
- make
- make test
- sudo make install
- cd
- cd build/akosoj/TechProject

- cd curl-7.54.0
- ./configure --with-ssl --disable-ftp --disable-file --disable-ldap --disable-dict --disable-telnet --disable-tftp --disable-rtsp --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-ares --disable-debug --without-zlib --without-libidn --without-librtmp
- make
- sudo make install
- ls
- cd
- ls
- cd
- ls

- find -name libcurl.a
- find -name *.a
- find -name *.lib

- cd build/akosoj/TechProject
- mkdir build
- cd build
- cmake .. && make
